import { englishCommonWordEntries } from './datasets/englishCommonWords.js';
import { topikAdvancedWordEntries } from './datasets/topikAdvancedWords.js';

const DEFAULT_STATUS = 'Chưa thuộc';

const numberWords = [
  ['zero', 'Num', 'số không'],
  ['one', 'Num', 'số một'],
  ['two', 'Num', 'số hai'],
  ['three', 'Num', 'số ba'],
  ['four', 'Num', 'số bốn'],
  ['five', 'Num', 'số năm'],
  ['six', 'Num', 'số sáu'],
  ['seven', 'Num', 'số bảy'],
  ['eight', 'Num', 'số tám'],
  ['nine', 'Num', 'số chín'],
  ['ten', 'Num', 'số mười'],
  ['eleven', 'Num', 'số mười một'],
  ['twelve', 'Num', 'số mười hai'],
  ['thirteen', 'Num', 'số mười ba'],
  ['fourteen', 'Num', 'số mười bốn'],
  ['fifteen', 'Num', 'số mười lăm'],
  ['sixteen', 'Num', 'số mười sáu'],
  ['seventeen', 'Num', 'số mười bảy'],
  ['eighteen', 'Num', 'số mười tám'],
  ['nineteen', 'Num', 'số mười chín'],
  ['twenty', 'Num', 'số hai mươi'],
  ['twenty-one', 'Num', 'số hai mươi mốt'],
  ['twenty-two', 'Num', 'số hai mươi hai'],
  ['twenty-three', 'Num', 'số hai mươi ba'],
  ['twenty-four', 'Num', 'số hai mươi bốn'],
  ['twenty-five', 'Num', 'số hai mươi lăm'],
  ['twenty-six', 'Num', 'số hai mươi sáu'],
  ['twenty-seven', 'Num', 'số hai mươi bảy'],
  ['twenty-eight', 'Num', 'số hai mươi tám'],
  ['twenty-nine', 'Num', 'số hai mươi chín'],
  ['thirty', 'Num', 'số ba mươi'],
  ['thirty-one', 'Num', 'số ba mươi mốt'],
  ['thirty-two', 'Num', 'số ba mươi hai'],
  ['thirty-three', 'Num', 'số ba mươi ba'],
  ['thirty-four', 'Num', 'số ba mươi bốn'],
  ['thirty-five', 'Num', 'số ba mươi lăm'],
  ['thirty-six', 'Num', 'số ba mươi sáu'],
  ['thirty-seven', 'Num', 'số ba mươi bảy'],
  ['thirty-eight', 'Num', 'số ba mươi tám'],
  ['thirty-nine', 'Num', 'số ba mươi chín'],
  ['forty', 'Num', 'số bốn mươi'],
  ['forty-one', 'Num', 'số bốn mươi mốt'],
  ['forty-two', 'Num', 'số bốn mươi hai'],
  ['forty-three', 'Num', 'số bốn mươi ba'],
  ['forty-four', 'Num', 'số bốn mươi bốn'],
  ['forty-five', 'Num', 'số bốn mươi lăm'],
  ['forty-six', 'Num', 'số bốn mươi sáu'],
  ['forty-seven', 'Num', 'số bốn mươi bảy'],
  ['forty-eight', 'Num', 'số bốn mươi tám'],
  ['forty-nine', 'Num', 'số bốn mươi chín'],
  ['fifty', 'Num', 'số năm mươi'],
  ['fifty-one', 'Num', 'số năm mươi mốt'],
  ['fifty-two', 'Num', 'số năm mươi hai'],
  ['fifty-three', 'Num', 'số năm mươi ba'],
  ['fifty-four', 'Num', 'số năm mươi bốn'],
  ['fifty-five', 'Num', 'số năm mươi lăm'],
  ['fifty-six', 'Num', 'số năm mươi sáu'],
  ['fifty-seven', 'Num', 'số năm mươi bảy'],
  ['fifty-eight', 'Num', 'số năm mươi tám'],
  ['fifty-nine', 'Num', 'số năm mươi chín'],
  ['sixty', 'Num', 'số sáu mươi'],
  ['sixty-one', 'Num', 'số sáu mươi mốt'],
  ['sixty-two', 'Num', 'số sáu mươi hai'],
  ['sixty-three', 'Num', 'số sáu mươi ba'],
  ['sixty-four', 'Num', 'số sáu mươi bốn'],
  ['sixty-five', 'Num', 'số sáu mươi lăm'],
  ['sixty-six', 'Num', 'số sáu mươi sáu'],
  ['sixty-seven', 'Num', 'số sáu mươi bảy'],
  ['sixty-eight', 'Num', 'số sáu mươi tám'],
  ['sixty-nine', 'Num', 'số sáu mươi chín'],
  ['seventy', 'Num', 'số bảy mươi'],
  ['seventy-one', 'Num', 'số bảy mươi mốt'],
  ['seventy-two', 'Num', 'số bảy mươi hai'],
  ['seventy-three', 'Num', 'số bảy mươi ba'],
  ['seventy-four', 'Num', 'số bảy mươi bốn'],
  ['seventy-five', 'Num', 'số bảy mươi lăm'],
  ['seventy-six', 'Num', 'số bảy mươi sáu'],
  ['seventy-seven', 'Num', 'số bảy mươi bảy'],
  ['seventy-eight', 'Num', 'số bảy mươi tám'],
  ['seventy-nine', 'Num', 'số bảy mươi chín'],
  ['eighty', 'Num', 'số tám mươi'],
  ['eighty-one', 'Num', 'số tám mươi mốt'],
  ['eighty-two', 'Num', 'số tám mươi hai'],
  ['eighty-three', 'Num', 'số tám mươi ba'],
  ['eighty-four', 'Num', 'số tám mươi bốn'],
  ['eighty-five', 'Num', 'số tám mươi lăm'],
  ['eighty-six', 'Num', 'số tám mươi sáu'],
  ['eighty-seven', 'Num', 'số tám mươi bảy'],
  ['eighty-eight', 'Num', 'số tám mươi tám'],
  ['eighty-nine', 'Num', 'số tám mươi chín'],
  ['ninety', 'Num', 'số chín mươi'],
  ['ninety-one', 'Num', 'số chín mươi mốt'],
  ['ninety-two', 'Num', 'số chín mươi hai'],
  ['ninety-three', 'Num', 'số chín mươi ba'],
  ['ninety-four', 'Num', 'số chín mươi bốn'],
  ['ninety-five', 'Num', 'số chín mươi lăm'],
  ['ninety-six', 'Num', 'số chín mươi sáu'],
  ['ninety-seven', 'Num', 'số chín mươi bảy'],
  ['ninety-eight', 'Num', 'số chín mươi tám'],
  ['ninety-nine', 'Num', 'số chín mươi chín'],
  ['one hundred', 'Num', 'một trăm'],
  ['one thousand', 'Num', 'một nghìn'],
  ['ten thousand', 'Num', 'mười nghìn'],
  ['one hundred thousand', 'Num', 'một trăm nghìn'],
  ['one million', 'Num', 'một triệu'],
  ['ten million', 'Num', 'mười triệu'],
  ['one hundred million', 'Num', 'một trăm triệu'],
  ['one billion', 'Num', 'một tỷ'],
  ['first', 'Ord', 'thứ nhất'],
  ['second', 'Ord', 'thứ hai'],
  ['third', 'Ord', 'thứ ba'],
  ['fourth', 'Ord', 'thứ tư'],
  ['fifth', 'Ord', 'thứ năm'],
  ['sixth', 'Ord', 'thứ sáu'],
  ['seventh', 'Ord', 'thứ bảy'],
  ['eighth', 'Ord', 'thứ tám'],
  ['ninth', 'Ord', 'thứ chín'],
  ['tenth', 'Ord', 'thứ mười'],
  ['eleventh', 'Ord', 'thứ mười một'],
  ['twelfth', 'Ord', 'thứ mười hai'],
  ['thirteenth', 'Ord', 'thứ mười ba'],
  ['fourteenth', 'Ord', 'thứ mười bốn'],
  ['fifteenth', 'Ord', 'thứ mười lăm'],
  ['sixteenth', 'Ord', 'thứ mười sáu'],
  ['seventeenth', 'Ord', 'thứ mười bảy'],
  ['eighteenth', 'Ord', 'thứ mười tám'],
  ['nineteenth', 'Ord', 'thứ mười chín'],
  ['twentieth', 'Ord', 'thứ hai mươi'],
  ['twenty-first', 'Ord', 'thứ hai mươi mốt'],
  ['twenty-second', 'Ord', 'thứ hai mươi hai'],
  ['twenty-third', 'Ord', 'thứ hai mươi ba'],
  ['twenty-fourth', 'Ord', 'thứ hai mươi tư'],
  ['twenty-fifth', 'Ord', 'thứ hai mươi lăm'],
  ['twenty-sixth', 'Ord', 'thứ hai mươi sáu'],
  ['twenty-seventh', 'Ord', 'thứ hai mươi bảy'],
  ['twenty-eighth', 'Ord', 'thứ hai mươi tám'],
  ['twenty-ninth', 'Ord', 'thứ hai mươi chín'],
  ['thirtieth', 'Ord', 'thứ ba mươi'],
  ['fortieth', 'Ord', 'thứ bốn mươi'],
  ['fiftieth', 'Ord', 'thứ năm mươi'],
  ['sixtieth', 'Ord', 'thứ sáu mươi'],
  ['seventieth', 'Ord', 'thứ bảy mươi'],
  ['eightieth', 'Ord', 'thứ tám mươi'],
  ['ninetieth', 'Ord', 'thứ chín mươi'],
  ['one hundredth', 'Ord', 'thứ một trăm'],
];

function createWords(entries, prefix) {
  return entries.map(([term, pos, meaning], index) => ({
    id: `${prefix}_${index + 1}`,
    term,
    pos,
    meaning,
    status: DEFAULT_STATUS,
  }));
}

function chunkWords(entries, { idPrefix, titlePrefix, language, chunkSize }) {
  const chunks = [];

  for (let index = 0; index < entries.length; index += chunkSize) {
    const chunk = entries.slice(index, index + chunkSize);
    const volume = String(Math.floor(index / chunkSize) + 1).padStart(2, '0');

    chunks.push({
      id: `${idPrefix}_${volume}`,
      title: `${titlePrefix} ${volume}`,
      language,
      words: createWords(chunk, `${idPrefix}_${volume}`),
    });
  }

  return chunks;
}

export const demoData = [
  {
    id: 'en_numbers_complete',
    title: 'English: Numbers 0-100 + Ordinals',
    language: 'en',
    words: createWords(numberWords, 'en_numbers'),
  },
  ...chunkWords(englishCommonWordEntries, {
    idPrefix: 'en_common_1000',
    titlePrefix: 'English: 1000 Common Words',
    language: 'en',
    chunkSize: 100,
  }),
  ...chunkWords(topikAdvancedWordEntries, {
    idPrefix: 'ko_topik_advanced',
    titlePrefix: 'Korean: TOPIK 5-6 Advanced',
    language: 'ko',
    chunkSize: 80,
  }),
];
